lang: en
name: Nera
robots: index,follow

translations:
  en:
    app_description: Nera is an easy to use and light weight static site generator
    app_keywords: nera, static site generator, easy, light weight
